language: python
python: 3.10
cache: pip

env:
  - TOXENV=py310
  - TOXENV=style

install:
  - travis_retry pip install tox

script:
  - tox

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.10
